//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 11:10:36 AM CEST 
//


package it.polito.dp2.RNS.sol3.service.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NewVehicle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewVehicle">
 *   &lt;complexContent>
 *     &lt;extension base="{}IdentifiedEntity">
 *       &lt;sequence>
 *         &lt;element name="suggestedPath" type="{}SuggestedPath"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewVehicle", propOrder = {
    "suggestedPath"
})
public class NewVehicle
    extends IdentifiedEntity
{

    @XmlElement(required = true)
    protected SuggestedPath suggestedPath;

    /**
     * Gets the value of the suggestedPath property.
     * 
     * @return
     *     possible object is
     *     {@link SuggestedPath }
     *     
     */
    public SuggestedPath getSuggestedPath() {
        return suggestedPath;
    }

    /**
     * Sets the value of the suggestedPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuggestedPath }
     *     
     */
    public void setSuggestedPath(SuggestedPath value) {
        this.suggestedPath = value;
    }

}
