//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.30 at 11:10:36 AM CEST 
//


package it.polito.dp2.RNS.sol3.service.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.sol3.service.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.sol3.service.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link ParkingAreas }
     * 
     */
    public ParkingAreas createParkingAreas() {
        return new ParkingAreas();
    }

    /**
     * Create an instance of {@link NewVehicle }
     * 
     */
    public NewVehicle createNewVehicle() {
        return new NewVehicle();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link RoadSegments }
     * 
     */
    public RoadSegments createRoadSegments() {
        return new RoadSegments();
    }

    /**
     * Create an instance of {@link RoadSegment }
     * 
     */
    public RoadSegment createRoadSegment() {
        return new RoadSegment();
    }

    /**
     * Create an instance of {@link Gate }
     * 
     */
    public Gate createGate() {
        return new Gate();
    }

    /**
     * Create an instance of {@link Places }
     * 
     */
    public Places createPlaces() {
        return new Places();
    }

    /**
     * Create an instance of {@link GenericPlaces }
     * 
     */
    public GenericPlaces createGenericPlaces() {
        return new GenericPlaces();
    }

    /**
     * Create an instance of {@link Vehicles }
     * 
     */
    public Vehicles createVehicles() {
        return new Vehicles();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link Entrance }
     * 
     */
    public Entrance createEntrance() {
        return new Entrance();
    }

    /**
     * Create an instance of {@link ParkingArea }
     * 
     */
    public ParkingArea createParkingArea() {
        return new ParkingArea();
    }

    /**
     * Create an instance of {@link PagedResponse }
     * 
     */
    public PagedResponse createPagedResponse() {
        return new PagedResponse();
    }

    /**
     * Create an instance of {@link IdentifiedEntity }
     * 
     */
    public IdentifiedEntity createIdentifiedEntity() {
        return new IdentifiedEntity();
    }

    /**
     * Create an instance of {@link GenericPlace }
     * 
     */
    public GenericPlace createGenericPlace() {
        return new GenericPlace();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Gates }
     * 
     */
    public Gates createGates() {
        return new Gates();
    }

    /**
     * Create an instance of {@link SuggestedPath }
     * 
     */
    public SuggestedPath createSuggestedPath() {
        return new SuggestedPath();
    }

}
